pull_request_rules:
  - name: dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      queue:
        name: default
        method: squash
queue_rules:
  - name: default
    conditions: []
