version: 2
builds:
  - id: schemat
    binary: schemat
    builder: rust
    command: build
    flags: --release
    targets:
      - aarch64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
      - x86_64-unknown-linux-gnu
